spring.application.name=demo

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/eventdb
spring.datasource.username=postgres

#everybody reset their paasssword in pgadmi. Go to querry tool write this querry ALTER USER postgres WITH PASSWORD 'test123';
spring.datasource.password=test123
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect